### ISSUE TITLE
Consider using Profile-Guided Optimization (PGO) 

### ISSUE THREAD

**Issue by zamazan4ik** [apache/horaedb#1051]
### Describe This Problem

Not a problem - just an idea of how to improve the performance of the database.

### Proposal

Hi!

According to my tests, Profile-Guided Optimization (PGO) usually helps a lot with database - see my tests [here](https://github.com/zamazan4ik/awesome-pgo/). I think can interesting to test this approach on CeresDB as well.

**Comment by ShiKaiWi** [comment]
@zamazan4ik It looks great! I'll spend some time to figure out how to use it.
