### ISSUE TITLE
Release all clients' version

### ISSUE THREAD

**Issue by tanruixiang** [apache/horaedb#1392]
### Describe This Problem

We need new version to replace something like `import " github.com/CeresDB/horaedb-client-go/horaedb"`

### Proposal

- [ ] https://github.com/apache/incubator-horaedb-client-java
- [x] https://github.com/apache/incubator-horaedb-client-rs
- [ ] https://github.com/apache/incubator-horaedb-client-go
- [x] https://github.com/apache/incubator-horaedb-client-py

**Comment by tanruixiang** [comment]
related https://github.com/apache/incubator-horaedb/pull/1387

**Comment by jiacai2050** [comment]
Python/Rust client are released, the others are in maintaining status, so have no plan to release them.
