### ISSUE TITLE
repo still has CLAassistant from pre-transfer legacy

### ISSUE THREAD

**Issue by tanruixiang** [apache/horaedb#1449]
### Describe this problem
New contributor still need to sign CLA.
https://github.com/apache/incubator-horaedb/pull/1448

**Comment by tanruixiang** [comment]
@chunshao90 please check it, if it can't be solved  by ppmc, we need to create a new issue in infra.

**Comment by tanruixiang** [comment]
https://issues.apache.org/jira/browse/INFRA-25431?filter=-2

**Comment by jiacai2050** [comment]
New PR show CLA is gone.
