### ISSUE TITLE
Tracking issue for horaectl features

### ISSUE THREAD

**Issue by Rachelint** [apache/horaedb#1502]
### Describe This Problem

Collect needed features for horaectl here.
## Horaemeta side

- [ ] Support listing all stale table metas(generated from table creation failure)

## Horaedb side

- [ ] Support cleaning flush failure status

### Proposal

Build them into horaectl.

**Comment by irenjj** [comment]
can i take Horaedb side task?

**Comment by Rachelint** [comment]
> can i take Horaedb side task?

Sure, feel free to take it.

**Comment by jiacai2050** [comment]
It's has been silent for a while, closing.
