### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by Shylock-Hg** [apache/horaedb#1506]
### Describe this problem

```
 /home/shylock/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/db/db_impl/db_impl.cc:1353:23: error: redundant move in return statement [-Werror=redundant-move]
   1353 |       return std::move(io_s);
```

### Server version

44caa997e37991e570741c3da6c961563569da42

### Steps to reproduce

1. Build with 

```
c (SUSE Linux) 13.2.1 20240206 [revision 67ac78caf31f7cb3202177e6428a46d829b70f23]
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Or maybe any new c++ compiler.

### Expected behavior

Build success.

**Comment by jiacai2050** [comment]
> Or maybe any new c++ compiler.

Yes, rocksdb require a latest C++ compiler, gcc 8 or clang 16 should work.

**Comment by jiacai2050** [comment]
Your version seems too new, try downgrade, or you can try build rust-rocksdb directly
https://github.com/tikv/rust-rocksdb

if it works against latest commit, we can bump our dependency.

**Comment by jiacai2050** [comment]
Rocksdb is not need any more, so this issue also disappear.
