### ISSUE TITLE
benchmark failed

### ISSUE THREAD

**Issue by zealchen** [apache/horaedb#1512]
### Describe this problem

Run benchmark with default config failed. Err msg is like:

1. Missing field.
Failed to parse config.: ParseToml { path: "/Users/chenmian.cm/Projects/incubator-horaedb/src/benchmarks/config/bench.toml", source: Error { inner: Error { inner: TomlError { message: "missing field `num_rows_per_row_group`", original: Some("# Licensed to the Apache Software Foundation (ASF) under one\n# or more contributor license agreements.  See the NOTICE file\n# distributed with this work for additional information\n# regarding copyright ownership.  The ASF licenses this file\n# to you under the Apache License, Version 2.0 (the\n# \"License\"); you may not use this file except in compliance\n# with the License.  You may obtain a copy of the License at\n#\n#   http://www.apache.org/licenses/LICENSE-2.0\n#\n# Unless required by applicable law or agreed to in writing,\n# software distributed under the License is distributed on an\n# \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY\n# KIND, either express or implied.  See the License for the\n# specific language governing permissions and limitations\n# under the License.\n\n[sst_bench]\nstore_path = \"/path/to/data/1/1\"\nsst_file_name = \"37.sst\"\nruntime_thread_num = 1\nbench_measurement_time = \"30s\"\nbench_sample_size = 30\nmax_projections = 5\nread_batch_row_num = 8192\nis_async = false\nreverse = false\n\n[sst_bench.predicate]\n# start_time_ms = 0\nstart_time_ms = 1632985200000\n# end_time_ms = 0\nend_time_ms = 1632985800000\n\n[merge_sst_bench]\nstore_path = \"/path/to/data\"\nspace_id = 1\ntable_id = 1\nsst_file_ids = [ 34, 37 ]\nruntime_thread_num = 1\nbench_measurement_time = \"30s\"\nbench_sample_size = 30\nmax_projections = 5\nread_batch_row_num = 500\nsst_level = 0\n\n[merge_sst_bench.predicate]\nstart_time_ms = 0\n# start_time_ms = 1632985200000\nend_time_ms = 0\n# end_time_ms = 1632985800000\n\n[scan_memtable_bench]\nstore_path = \"/path/to/data/1/1\"\nsst_file_name = \"37.sst\"\nruntime_thread_num = 1\nmax_projections = 5\narena_block_size = \"64M\"\n\n[merge_memtable_bench]\nstore_path = \"/path/to/data\"\nspace_id = 1\ntable_id = 1\nsst_file_ids = [ 37 ]\nruntime_thread_num = 1\nmax_projections = 5\narena_block_size = \"64M\"\n\n[wal_write_bench]\nbench_measurement_time = \"60s\"\nbench_sample_size = 60\nbatch_size = 512\nvalue_size = 1024\n\n[replay_bench]\nbench_measurement_time = \"3s\"\nbench_sample_size = 10"), keys: ["sst_bench"], span: Some(786..1011) } } }, backtrace: Backtrace(   0: backtrace::backtrace::libunwind::trace

2. Invalid config.
thread 'main' panicked at src/benchmarks/src/parquet_bench.rs:49:83:
called `Result::unwrap()` on an `Err` value: Generic { store: "LocalFileSystem", source: UnableToCanonicalize { path: "/path/to/data/1/1", source: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }

### Server version

HoraeDB Server 
Version: 2.0.0
Git commit: cfbbe3d3
Git branch: feat_replay_benchmark
Opt level: 0
Rustc version: 1.77.0-nightly
Target: x86_64-apple-darwin
Build date: 2024-04-10T07:38:04.708239000Z

### Steps to reproduce

ANALYTIC_BENCH_CONFIG_PATH=/path/to/incubator-horaedb/src/benchmarks/config/bench.toml cargo bench --bench bench -p benchmarks -- bench_parquet

**Comment by jiacai2050** [comment]
```
UnableToCanonicalize { path: "/path/to/data/1/1", s
```

It seems you need to update config to set it to a real path.
