### ISSUE TITLE
Adapt to a variety of object storage.

### ISSUE THREAD

**Issue by ZuLiangWang** [apache/horaedb#1519]
### Describe This Problem

Currently, HoraeDB only supports Aliyun OSS and AWS S3 as object storage implementations. We hope to support more object stores to facilitate deployment in various environments. We found that some object storage implementations do not support multipartupload, and currently HoraeDB uses For this interface implementation, we need to replace it with put.

### Proposal

Use object storage interface `put` to simulate `multipartupload`.

**Comment by poelzi** [comment]
I suggest using the [object-store](https://crates.io/crates/object-store) crate.
TiKV support would be awesome

**Comment by jiacai2050** [comment]
We already switch opendal for object store access, so this is not required.
