### ISSUE TITLE
SDK supports writing `Date` type

### ISSUE THREAD

**Issue by chunshao90** [apache/horaedb#1549]
### Describe This Problem

The document supports the Date type, but the SDK does not support writing the Date type.
Ref: https://horaedb.apache.org/docs/user-guide/sql/model/data_types/

### Proposal

SDK supports writing `Date` type.

- [ ] Java
- [ ] Pthon
- [ ] Golang
- [ ] Rust

### Additional Context

This is what server defines:

https://github.com/apache/horaedb/blob/a57770679aa7482faeed232567d34c96b5bc387b/src/common_types/src/datum.rs#L441-L449

**Comment by adi-kmt** [comment]
Hey @chunshao90 can I pick this up?

**Comment by jiacai2050** [comment]
@adi-kmt Just go ahead, which sdk are you interested at?

**Comment by adi-kmt** [comment]
Can start with Go and once I'm done with that can pick up rust and so on.

**Comment by jiacai2050** [comment]
Sounds good, let me know if you have any problems.

**Comment by jiacai2050** [comment]
@adi-kmt Any progress?

**Comment by adi-kmt** [comment]
Sorry, got a bit busy with work
Just confirming @jiacai2050 , is the sdk the same inside the `integration_test/sdk`? Or is there some other path. Asking since i could only find one `*.java` file in the code, but no `*.py` file in that integration test

**Comment by jiacai2050** [comment]
They are in different repository, please see https://horaedb.apache.org/docs/user-guide/sdk/
