### ISSUE TITLE
Cli tools to decode wal segment

### ISSUE THREAD

**Issue by jiacai2050** [apache/horaedb#1567]
### Describe This Problem

I'm excited to share that we've successfully implemented a local Write-Ahead Log (WAL) following the completion of #1566. While we haven't conducted extensive performance benchmarking yet, our initial tests suggest that our implementation is performing comparably to the one based on RocksDB. This marks a significant milestone in our project's development, and we're looking forward to further optimizing and testing this new feature.

### Proposal

In order to trouble shoot WAL issues, we need a cli tool to decode wal segment, to include at least following infos:
- segment version
- min/max seq of each table

**Comment by zealchen** [comment]
Nice. Let me handle this one.

**Comment by jiacai2050** [comment]
Thanks, you can add another project here https://github.com/apache/horaedb/tree/main/src/tools/src/bin
