### ISSUE TITLE
Type `test` is not supported in pr title

### ISSUE THREAD

**Issue by LeslieKid** [apache/horaedb#1575]
### Describe This Problem

I encountered an error in pr #1573 when run Checks `check-pr-title`:
`PR title does not follow the convention, the pattern: ^(feat|fix|docs|refactor|chore)((.+))?!?: .+$`
because the pr title is **test: add integration test for compaction offload**, not match patter above.

But I found that `test` type is supported when reading [convential commit guide in official document](https://horaedb.apache.org/docs/dev/conventional_commit/). Similar situation include `style` and `build` type.

So I think these types should be supported in `check-pr-title`.

### Proposal
If `test`, `style` and `build` can be supported, we can add these types in the `check-pr-title` part in `.github/workflows/check-pr-title.yml`.

**Comment by jiacai2050** [comment]
Good suggestion, I think we can update the pattern to include test, style and build.
