### ISSUE TITLE
Support INSERT INTO SELECT

### ISSUE THREAD

**Issue by jiacai2050** [apache/horaedb#557]
### Describe This Problem

Enhance SQL support.

`INSERT INTO SELECT` is useful to migrate table, benchmark(to quickly generate lots of data).

### Proposal

Implement this SQL syntax.
```sql
INSERT INTO table2 (column1, column2, column3, ...)
SELECT column1, column2, column3, ...
FROM table1
WHERE condition;
```
### Additional Context
- https://dev.mysql.com/doc/refman/8.0/en/insert-select.html
- https://www.w3schools.com/mysql/mysql_insert_into_select.asp

**Comment by caicancai** [comment]
Hi, I'm interested in this let me try, but this one may take a little time

**Comment by jiacai2050** [comment]
Thanks, assigned.

You need to how horaedb parse sql, how a plan is created and executed. This is indeed a non-trivial task, feel free to ask any questions when you are in trouble.

**Comment by jiacai2050** [comment]
@caicancai Hi, a few weeks passed, how's it going? Any problems?

**Comment by caicancai** [comment]
> @caicancai Hi, a few weeks passed, how's it going? Any problems?

There doesn't seem to be any progress. I was busy with work in December. I'm sorry for that. I may start this part of the work on New Year's Day, if this feature is not urgent.

**Comment by jiacai2050** [comment]
Hi, take you time, just want to know if there is any problems.

**Comment by jiacai2050** [comment]
You can join our slack channel to discuss with us.
- https://github.com/apache/incubator-horaedb?tab=readme-ov-file#contributing

**Comment by caicancai** [comment]
@jiacai2050 Hello, I tried it during the holiday. I expected that this feature would take up a lot of my energy. Since I have been busy recently, I may not have so much energy. I chose to give up this feature. I am very sorry for taking up so much time.

**Comment by jiacai2050** [comment]
Thanks for trying out, This task is a little complex, you need to understand how query and write works at a whole level.

> PS: I remove the `good first issue` tag.

**Comment by dracoooooo** [comment]
Hi @jiacai2050, I'd like to take this task.

**Comment by jiacai2050** [comment]
👍 Much appreciated.
