### ISSUE TITLE
Table partition's design is contradictory

### ISSUE THREAD

**Issue by kamille126** [apache/horaedb#573]
### Describe This Problem

As I see, we want to treat the `partitioned table` same as the `data table` like traditional standalone database.
But in `ceresmeta`, `data table` is not allowed for existing in multiple shards, and this is allowed for `partitioned table`(make sense by a hard code scheduled rule: two shards which has the same `partitioned table` can not be scheduled to the same node).
So, it make me confused: how we want to treat the `partitioned table` and `data table`, same or different?

### Proposal

I think we should make the target clear, and refactor according to our target.
1. treat them same
`Data table` can exist in multiple shards, too. And since we promote the concept `shard` to admin tables, we should admin the all tables following the level: node -> shard -> table, it makes no sense to admin the `partitioned table` directly according to nodes if we decide to treat them same.
+  In `ceresdb,` we add `shard` information in all the memory data structure for managing.
+ In `ceresmeta`, we try best to make the shards(has the `partitioned table`) no in the same nodes(but it is allowed to happen).
problems: because we need to write the `partitioned table`, we should sovle the multiple leaders problem in later development.

2. treat them different
`Partitioned table` is just a logical concept, it is not managed by the same way as the `data table` no matter in `ceresdb` or `ceresmeta`.
+ In `ceresdb,` we treat them different in the top level, for example, desgin a independent `catalog` for `Partitioned table`.
+ In `ceresmeta`, we don't schedule the `partitioned table` by the same way of the `data table`, new scheuling way is needed.
problems: the architecture is a bit messy.

**Comment by chunshao90** [comment]
Can we consider that `PartitionTable` is a logical concept, which is equivalent to a kind of calculation. 
We abstract a proxy role for stateless capabilities such as calculation, so PartitionTable can be scheduled on `proxy` nodes. 
The node where the actual data table resides is called a `datanode`. 
`ceresmeta` maintains different logic for scheduling `proxy` and `datanode`.

**Comment by kamille126** [comment]
> Can we consider that `PartitionTable` is a logical concept, which is equivalent to a kind of calculation. We abstract a proxy role for stateless capabilities such as calculation, so PartitionTable can be scheduled on `proxy` nodes. The node where the actual data table resides is called `datanode`. `ceresmeta` maintains different logic for scheduling `proxy` and `datanode`.

Yep, I prefer the second way, too.
But should we place the table partition logic into `analytic_engine`?
We do it now for treating it a normal table, but some trouble has occurred now:
+ place the `remote client` and `router` into `instance` that makes the initialization code hard to write.
+ reuse the table recovering logic that leads to the multiple manifest writing problem.
Maybe, we shouldn't place it in `analytic_engine` actually.
