### ISSUE TITLE
RFC tracker: Prometheus read extension for CeresDB

### ISSUE THREAD

**Issue by waynexia** [apache/horaedb#90]
**RFC**
This is proposed in #79. See [rendered](https://github.com/waynexia/ceresdb/blob/rfc-prom-ext/docs/rfcs/20220702-prometheus-read-extension.md)

**Task List**
TBD

**Comment by jiacai2050** [comment]
This RFC is kinds of stale, users from community may prefer integrate with Prometheus 'natively', see https://github.com/CeresDB/ceresdb/issues/633.

Since this RFC is not getting any obvious progress, so I think we need to reconsider this.
