### ISSUE TITLE
Support write/query via OpenTSDB API

### ISSUE THREAD

**Issue by jiacai2050** [apache/horaedb#904]
### Describe This Problem

Currently there are three query language supported in CeresDB: SQL/InfluxQL/PromQL. It would be great to also support OpenTSBD query API.

### Proposal

There are many API in OpenTSDB, the following two API are most important, so we can first implement those.
- [ ] http://opentsdb.net/docs/build/html/api_http/query/index.html
- [x] http://opentsdb.net/docs/build/html/api_http/put.html

**Comment by parkma99** [comment]
I would like to work `query` api, I am newer fo this project, Could you give me some suggestion to start?😊

**Comment by jiacai2050** [comment]
Thanks for you interests, let us know when you have any problems.

**Comment by parkma99** [comment]
I find it's very hard to me current 😢😢，I give up to others this issue.

**Comment by jiacai2050** [comment]
@parkma99 😅 Thanks anyway, you can try other issue first.
- https://github.com/CeresDB/ceresdb/labels/contributor%20friendly

**Comment by jiacai2050** [comment]
[This docs](http://opentsdb.net/docs/build/html/user_guide/query/index.html) explain how opentsdb query is executed:

    Filtering

    Grouping

    Downsampling

    Interpolation

    Aggregation

    Rate Conversion

    Functions

    Expressions



Understanding the order of operations is important. When returning query results the following is the order in which processing takes place:
