### ISSUE TITLE
A large number of '\' in Java SDK error message

### ISSUE THREAD

**Issue by xzchaoo** [apache/horaedb#920]
### Describe this problem

The error message of the CeresDB SDK contains a large number of '\\'.

I create a table with 'value' field initialized with 'double' data type.
Then I write a record with value '{... my biz json content ...}', which is a json string.
CeresDB Java SDK reports an error. Ok. I know it's normal to report errors.
But, the error content contains a large number of '\\'.
**The longest line reaches 12MB.** But the length of my json is only a few thousand.

![image](https://github.com/CeresDB/ceresdb/assets/8319940/251ef2d0-1e36-416f-9b14-c3828785eb4c)

![image](https://github.com/CeresDB/ceresdb/assets/8319940/f4ea36a4-caa3-4f90-ab84-e0998ecf5962)

### Server version

Docker image ceresdb/ceresdb-server:v1.0.0
Java SDK: io.ceresdb:ceresdb-all:1.0.3

### Steps to reproduce

I create a table with 'value' field initialized with 'double' data type.
Then I write a record with value '{... my biz json content ...}', which is a json string.
CeresDB Java SDK reports an error. Ok. I know it's normal to report errors.
But, the error content contains a large number of '\\'.
**The longest line reaches 12MB.** But the length of my json is only a few thousand.

### Expected behavior

CeresDB Java SDK reports an error with better error message.

**Comment by ShiKaiWi** [comment]
I guess this seems a bug in the java SDK. Let's try to reproduce it. @xzchaoo Could please provide your table schema or the create table SQL?
