### ISSUE TITLE
Use `tracing` as our logger rather than `slog`

### ISSUE THREAD

**Issue by Rachelint** [apache/horaedb#933]
### Describe This Problem
`slog` is an outdated crate maintained by nobody now. And the most popular one is tokio's `tracing`. In fact, we have used `tracing` in our project but not include its logger, how about let's  make use of it. 

### Proposal

Maybe can make it referring to [influxdb_iox](https://github.com/influxdata/influxdb)

**Comment by ShiKaiWi** [comment]
I'll vote for it if there is no performance issue.
