### ISSUE TITLE
Limit query is slow

### ISSUE THREAD

**Issue by ShiKaiWi** [apache/horaedb#997]
### Describe This Problem

In most cases, limit query is expected to be very fast. However, when there are too many segments, it will be very slow even if  the query is limit by 1.

### Proposal

Make it run as fast as possible for limit query.

**Comment by jiacai2050** [comment]
> In most cases, limit query is expected to be very fast.

I think you are meaning query without group by and order by.

For this to work, our executor should support pass result in a streaming way, which is what we have now, so this should be improved without too much work.
